### PR TITLE
Message navigation commands

### PR DESCRIPTION
**Pull request by greensnark**
Atom commands to go to next/prev message.

This is handy when the message pane is used for error/warning messages.
    
As an example of consuming this service, see https://github.com/greensnark/go-plus/commit/9263e307f123cc05ff383001e213118317f73887

This commit is the equivalent of https://github.com/tcarlsen/atom-message-panel/pull/76 and does these things:

- Adds a single entry point to the service provider that returns the message panel and the plain and line views in one call; most users of the message panel service will want one or other of the view classes in addition to the message panel. Having to consume multiple services for the message panel is a little awkward.

- Toss the placeholder specs generated by the scaffolding, those didn't pass.

- Adds atom commands "message-panel:next-message" and
  "message-panel:previous-message" to go to the previous and next messages.
  The active message panel keeps track of the current message.  The *last
  attached* message panel responds to these commands.
    
- Highlights messages when the editor cursor moves to the line mentioned in the
  message(s).

- Adjust .less styles slightly so that highlighted messages don't jump around quite so visibly. The regular -> bold font change still causes a little distracting text movement, I'm open to suggestions on that.

### CODE REVIEW

**Comment by tcarlsen** [comment]
sry the delay

**Comment by tcarlsen** [comment]
I really hope you will try the service out and maybe help get it good enough to replace the npm version

**Comment by greensnark** [comment]
The service worked fine for me when I tested it with go-plus, but Joe is in the middle of rewriting go-plus, so I'm not sure when it can/will switch to the AMP service.

**Comment by tcarlsen** [comment]
fair enough. Want to rewrite my own packages to use this for better testing. But I have almost no free time to develop on these

**Pull request merged**
